### ISSUE TITLE
git2json crashes in rare case parse_message_line returns None 

### ISSUE THREAD

**Issue by clay-reed-a** [tarmstrong/git2json#11]
OS - `Linux crunchbang 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux`
Python - 2.7.2 

I went to take `git2json` for a spin on a repository with a long commit log to see how it would work. 

I chose the Rails repository, which contains the following commit: 

```
commit e04818d1b8de44d47003031791f142182320ed89
tree 3f56c6c53f914a2ed882e32a8a3438be619f8f17
parent 6cbec586731b7c5f293f2a7b6c7330c7181acdfe
author Jeremy Kemper <jeremy@bitsweat.net> 1348081584 -0700
committer Jeremy Kemper <jeremy@bitsweat.net> 1348081584 -0700

    Revert "Make sure :environment task is executed before db:schema:load or db:structure:load
"

    Breaks db:setup because it tries to load the environment before creating the database.

    This reverts commit 5ca11fefce6d83f5db399aa4412f1f1a0d42b2e6.

2   2   activerecord/lib/active_record/railties/databases.rake
```

I was unable to determine why, but, for some reason, there is a carriage return character between `load` and `"`. 

So calling `splitlines()` on

``` python
'''    Revert "Make sure :environment task is executed before db:schema:load or db:structure:load
"
    Yip yip yip
''' 
```

we get: 

``` python
['    Revert "Make sure :environment task is executed before db:schema:load or db:structure:load', '"', '    Yip yip yip']
```

But if you pass `parse_message_line` a string like `'"'`, it will return `None`, and `join` cannot handle lists with `None` in them. 

``` python
>>> l = ['fee', 'foo', 'fi', None] 
>>> "\n".join(l)
TypeError: sequence item 3: expected string, NoneType found
```

**Comment by tarmstrong** [comment]
@clay-reed-a thank you for the report. I believe I've fixed this issue, but let me know if it's still a problem. (I've taken forever to respond, so don't feel obliged to respond (: )
